//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumirTabla.ServiceTabla {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTabla.IServicioTabla")]
    public interface IServicioTabla {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTabla/GetSecuenciaTabla", ReplyAction="http://tempuri.org/IServicioTabla/GetSecuenciaTablaResponse")]
        int[] GetSecuenciaTabla(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTabla/GetSecuenciaTabla", ReplyAction="http://tempuri.org/IServicioTabla/GetSecuenciaTablaResponse")]
        System.Threading.Tasks.Task<int[]> GetSecuenciaTablaAsync(int numero);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioTablaChannel : ConsumirTabla.ServiceTabla.IServicioTabla, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioTablaClient : System.ServiceModel.ClientBase<ConsumirTabla.ServiceTabla.IServicioTabla>, ConsumirTabla.ServiceTabla.IServicioTabla {
        
        public ServicioTablaClient() {
        }
        
        public ServicioTablaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioTablaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioTablaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioTablaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int[] GetSecuenciaTabla(int numero) {
            return base.Channel.GetSecuenciaTabla(numero);
        }
        
        public System.Threading.Tasks.Task<int[]> GetSecuenciaTablaAsync(int numero) {
            return base.Channel.GetSecuenciaTablaAsync(numero);
        }
    }
}
